### ISSUE TITLE
sometimes save comments fails

### ISSUE THREAD

**Issue by ojanvafai** [esprehn/chromium-codereview#24]
Sometimes I click the save comments button. It shows the butterbar, then hides the butterbar, but doesn't un-editablify the textarea. Clicking the button again works.

**Comment by esprehn** [comment]
Yeah I've noticed this too. If you click "save" again you'll actually end up with the comment twice. It seems to happen because I have to parse a big chunk of HTML whenever you save comments since Rietveld doesn't have a JSON API for adding them. I tried to get jrobbins to add a new API for this, but he was resistant. :(

**Comment by esprehn** [comment]
For reference that bug is going to be somewhere inside https://github.com/esprehn/chromium-codereview/blob/master/ui/model/patch_file.js#L64 or https://github.com/esprehn/chromium-codereview/blob/master/ui/model/patch_file_message.js#L31

I've seen an HTML parse error when this happens, I need to track down what's going on.

**Comment by esprehn** [comment]
Optimistically closing this, reopen if you see it again.
