### ISSUE TITLE
Improve the issue-need-my-input detection

### ISSUE THREAD

**Issue by jchaffraix** [esprehn/chromium-codereview#35]
The old UI would give information about whether someone already LGTM'ed a patch and whether some comment happened on the bug. I use these to quickly sort which issues require my attention and found them super useful.

**Comment by aarongable** [comment]
Commit 8377a93 is not actually a fix for this bug: the normal Rietveld UI bolds issues which have had activity since the last time you gave input. This new UI does not replicate that behavior.

Someone sends an issue to me for review. It is bold.
I send comments. It becomes non-bold.
They respond to my comments, or upload a new patchset, or anyone else also sends new comments. It becomes bold again.
