### ISSUE TITLE
Select All doesn't work

### ISSUE THREAD

**Issue by aarongable** [esprehn/chromium-codereview#50]
Select all / ctrl-A only selects text within the most recently focused element (e.g. a single message, a single file line, the commit message, the issue title, etc.). It doesn't appear to be possible to select across elements by any means.

**Comment by esprehn** [comment]
That's how Shadow DOM works and how native apps work. You can't select text between random UI controls in a native app. I don't know why you'd ever want Ctrl+A in Rietveld, for example in the old Rietveld it would select the entire app UI, everything from buttons to message summaries to headers.

**Comment by aarongable** [comment]
Then maybe it's just an issue of separation of elements in the Shadow DOM. You're right that select-all is not super useful in this context. However, related things are:
- Select all the text of all expanded messages.
- Select the filenames of all files in a patchset.
- Select multiple lines from Inbox display
  None of these are currently possible, since each message / filename / issue is its own element and select can't cross element boundaries.

**Comment by esprehn** [comment]
None of those things you're suggesting are possible in a native app. You can't select across emails in Gmail on Android and you can't select messages from the inbox. :)

Even if I wanted to though, Chrome doesn't allow selections across shadow roots since the Range API in the web doesn't understand them. There's nothing I can fix here until the web supports a better selection model.
