### ISSUE TITLE
Diff missing show context link on single @@ line

### ISSUE THREAD

**Issue by quisquous** [esprehn/chromium-codereview#59]
See https://codereview.chromium.org/334953003, patch set 3, cc/layers/picture_layer_impl.cc, line 404/396.  There's a @@ line there for the diff where normally a show context link is, but there isn't one on this line.

That said, the diff is only one line, so the @@ line should probably be elided entirely.

**Comment by esprehn** [comment]
Yeah that is goofy.

**Comment by esprehn** [comment]
Note that I can't elide the context lines without a better API from Rietveld that doesn't take so long to respond. I'd rather have some goofy lines like this instead of making loading all diffs slower. Eventually it'd be nice to be able to show +10 lines in every direction like Rietveld did for side-by-side.
